package bean.pojo;
// Generated Oct 15, 2022 4:01:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Payments generated by hbm2java
 */
public class Payments  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set transactionses = new HashSet(0);

    public Payments() {
    }

	
    public Payments(String name) {
        this.name = name;
    }
    public Payments(String name, Set transactionses) {
       this.name = name;
       this.transactionses = transactionses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }




}


