package bean.pojo;
// Generated Oct 15, 2022 4:01:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private Payments payments;
     private Products products;
     private Users users;
     private String name;
     private String email;
     private Long phoneNumber;
     private String address;
     private boolean paid;

    public Transactions() {
    }

	
    public Transactions(Payments payments, Products products, boolean paid) {
        this.payments = payments;
        this.products = products;
        this.paid = paid;
    }
    public Transactions(Payments payments, Products products, Users users, String name, String email, Long phoneNumber, String address, boolean paid) {
       this.payments = payments;
       this.products = products;
       this.users = users;
       this.name = name;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.address = address;
       this.paid = paid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Payments getPayments() {
        return this.payments;
    }
    
    public void setPayments(Payments payments) {
        this.payments = payments;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Long getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public boolean isPaid() {
        return this.paid;
    }
    
    public void setPaid(boolean paid) {
        this.paid = paid;
    }




}


