package bean.pojo;
// Generated Oct 15, 2022 4:01:07 PM by Hibernate Tools 4.3.1


import dao.PaymentsDao;
import dao.ProductsDao;
import dao.TransactionsDao;
import dao.UsersDao;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;

/**
 * Transactions generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Transactions  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private Payments payments;
     private int paymentId;
     private Products products;
     private String productName;
     private Users users;
     private int userId;
     private String name;
     private String email;
     private Long phoneNumber;
     private String address;
     private boolean paid;
     private List<Transactions> history;
     private boolean deleted;
     
     TransactionsDao dao = new TransactionsDao();
  
     public Transactions() {
    }
	
    public Transactions(Payments payments, Products products, boolean paid) {
        this.payments = payments;
        this.products = products;
        this.paid = paid;
    }
    public Transactions(Payments payments, Products products, Users users, String name, String email, Long phoneNumber, String address, boolean paid) {
       this.payments = payments;
       this.products = products;
       this.users = users;
       this.name = name;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.address = address;
       this.paid = paid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Payments getPayments() {
        return this.payments;
    }
    
    public void setPayments(Payments payments) {
        this.payments = payments;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Long getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public boolean isPaid() {
        return this.paid;
    }
    
    public void setPaid(boolean paid) {
        this.paid = paid;
    }

    public int getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public List<Transactions> getHistory() {
        return history;
    }

    public void setHistory(List<Transactions> history) {
        this.history = history;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    
    public String getHistory(int userId) {
        history = dao.getHistory(userId);
        
        
        return "history.xhtml";
    }

    public String create(Users user) {
        PaymentsDao payDao = new PaymentsDao();
        payments = payDao.getById(paymentId);
        ProductsDao proDao = new ProductsDao();
        products = proDao.getByProperty("name", productName);
        users = user;
        this.name = user.getName();
        this.email = user.getEmail();
        this.phoneNumber = user.getPhoneNumber();
        this.address = user.getAddress();
        
        boolean berhasil = dao.create(this);
        
        return berhasil ? "success.xhtml" : "error.xhtml";
    }

    public String delete(Transactions transaction, int userId) {
        deleted = dao.delete(transaction);
        history = dao.getHistory(userId);
        
        return "history.xhtml?id=" + userId + "&history-id=" + id + "&deleted=" + deleted; 
    }
}


