package bean.pojo;
// Generated Oct 15, 2022 4:01:07 PM by Hibernate Tools 4.3.1


import dao.TransactionsDao;
import dao.UsersDao;
import java.util.HashSet;
import java.util.Set;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

/**
 * Users generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class Users  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String password;
     private String name;
     private long phoneNumber;
     private String address;
     private Set transactionses = new HashSet(0);
     private boolean loginStatus;
     private boolean logoutStatus = true;
     
     UsersDao dao = new UsersDao();

    public Users() {
    }

	
    public Users(String email, String password, String name, long phoneNumber, String address) {
        this.email = email;
        this.password = password;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.address = address;
    }
    public Users(String email, String password, String name, long phoneNumber, String address, Set transactionses) {
       this.email = email;
       this.password = password;
       this.name = name;
       this.phoneNumber = phoneNumber;
       this.address = address;
       this.transactionses = transactionses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }

    public boolean isLoginStatus() {
        return loginStatus;
    }

    public void setLoginStatus(boolean loginStatus) {
        this.loginStatus = loginStatus;
    }

    public boolean isLogoutStatus() {
        return logoutStatus;
    }

    public void setLogoutStatus(boolean logoutStatus) {
        this.logoutStatus = logoutStatus;
    }
    
    public String login() {
        Users user = dao.login(email, password);
        this.id = user.id;
        this.email = user.email;
        this.password = user.password;
        this.name = user.name;
        this.phoneNumber = user.phoneNumber;
        this.address = user.address;
        this.loginStatus = true;
        this.logoutStatus = false;
        
        return "index.xhtml";
    }
    
    public String getProfile() {
        Users user = dao.getById(id);
        this.id = user.id;
        this.email = user.email;
        this.name = user.name;
        this.phoneNumber = user.phoneNumber;
        this.address = user.address;
        this.loginStatus = true;
        this.logoutStatus = false;
        
        return "profile.xhtml";
    }
    
    public String update() {
        boolean berhasil = dao.update(this);
        
        return berhasil ? "success.xhtml" : "error.xhtml";
    }
    
    public String logout() {
        dao.logout();
        
        return "/";
    }


}


